version: '3'
services:
  database:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
      - ./config/db/database_setup.sql:/docker-entrypoint-initdb.d/database_setup.sql # setup database on first start
  webrick:
    build: .
    volumes:
      - .:/buycotest
    ports:
      - 8000:8000
    links:
      - database:db_link
    depends_on:
      - database
volumes:
  database-data:
